insee:
  cog:
    communes:
      - url: https://www.insee.fr/fr/statistiques/fichier/3720946/communes-01042019-csv.zip
        date: 04/2019
        hash: d28deef5a8e402044984366acbcd308c90d1982f283991a747c6643922a20310
    cantons:
      - url: https://www.insee.fr/fr/statistiques/fichier/3720946/canton2019-csv.zip
        date: 01/2019
        hash: 2b8056f5988448c947f9cdbf701941a5bfcf93f41ca21c11c46c4659cf49c059
    arrondissements:
      - url: https://www.insee.fr/fr/statistiques/fichier/3720946/arrondissement2019-csv.zip
        date: 01/2019
        hash: bd451a13a3984d2d13ac1907b7e78cbf6405b166bc710db71b64c7a93f6d859e
    departements:
      - url: https://www.insee.fr/fr/statistiques/fichier/3720946/departement2019-csv.zip
        date: 01/2019
        hash: ffda417ca7a5e1dad1810e5952ee205e73adefa9a0503d77aeb69499aca15eba
    regions:
      - url: https://www.insee.fr/fr/statistiques/fichier/3720946/region2019-csv.zip
        date: 01/2019
        hash: 023f23a778fb16023c3f2fcfc2d62056a3594bf1f6219fed1283cd33820d69ee
    evenements_communes:
      - url: https://www.insee.fr/fr/statistiques/fichier/3720946/mvtcommune-01042019-csv.zip
        date: 04/2019
        hash: e6bba1d2564b564a6a4bbf19f340425c916cd9c05b02905a9842be5f70728808

  intercommunalite:
    epci:
      - url: https://www.insee.fr/fr/statistiques/fichier/2510634/Intercommunalite-Metropole_au_01-01-2019.zip
        date: 01/2019
        hash: e612f15879f01bde9d6984c95dea6edba6709d88df6e0d7166ab6a26f78a04a5

  decoupage_communal:
    - url: https://www.insee.fr/fr/statistiques/fichier/2028028/table-appartenance-geo-communes-19.zip
      date: 01/2019
      hash: af1a56188813d578dd07b5adc7f74c87e0a0b140049dc9e0c544f7b81f4610ca


ign:
  admin-express:
    version-cog:
      - url: ftp://Admin_Express_ext:Dahnoh0eigheeFok@ftp3.ign.fr/ADMIN-EXPRESS-COG_2-0__SHP__FRA_WGS84G_2019-09-24.7z.001
        date: 01/2019
        hash: ed8be4045813f50deb5659e401ee3cd389bcad7cabcc2e7baddaf76f3a232e37
    classique:
      - url: ftp://Admin_Express_ext:Dahnoh0eigheeFok@ftp3.ign.fr/ADMIN-EXPRESS_2-2__SHP__FRA_L93_2020-01-16.7z.001
        date: 01/2020
        hash: 635d5625ea0e4a311d8eb8af10c46fe081385e2840be2f558d457ef814038f20


interieur:
  resultats_electoraux:
    presidentielles:
      2017:
        tour1:
          - url: https://www.data.gouv.fr/s/resources/election-presidentielle-des-23-avril-et-7-mai-2017-resultats-definitifs-du-1er-tour-par-bureaux-de-vote/20170427-100955/PR17_BVot_T1_FE.txt
            date: 04/2017
            hash: 1eb1e4358a8af59ebc86ff7e0e4a2ee175f6cf516e4598cd955193064fc91e6a
            preparation: data_preparation.elections.scrutins_2017:clean_results
        tour2:
          - url: https://www.data.gouv.fr/s/resources/election-presidentielle-des-23-avril-et-7-mai-2017-resultats-definitifs-du-2nd-tour-par-bureaux-de-vote/20170511-093541/PR17_BVot_T2_FE.txt
            date: 05/2017
            hash: 2b6137b64957b9bfff24436cf859aad15e8b155b837b182eebff71c21fc82798
            preparation: data_preparation.elections.elections_2017:clean_results
    legislatives:
      2017:
        tour1:
          - url: https://www.data.gouv.fr/s/resources/elections-legislatives-des-11-et-18-juin-2017-resultats-par-bureaux-de-vote-du-1er-tour/20170613-100441/Leg_2017_Resultats_BVT_T1_c.txt
            date: 06/2017
            hash: f0e0d5149af2a52b843712329889f607efd589dd4836f0ec1334eb8b164e5fdb
            preparation: data_preparation.elections.elections_2017:clean_results
        tour2:
          - url: https://www.data.gouv.fr/s/resources/elections-legislatives-des-11-et-18-juin-2017-resultats-du-2nd-tour-par-bureaux-de-vote/20170620-094954/Leg_2017_Resultats_BVT_T2_c.txt
            date: 06/2017
            hash: 2d898b6bebcc401b79fe3ebbc0deb37d5dcc32c11ac3f5e8be0b0f006ee9eb8e
            preparation: data_preparation.elections.elections_2017:clean_results
    europeennes:
      2014:
        - url: https://www.data.gouv.fr/s/resources/elections-europeennes-2014-resultats-par-bureaux-de-vote/20150925-112120/ER14_BVOT.txt
          date: 25/09/2015
          hash: af1840b437db8a154f5b286c18a45d7534238ab8b9e73b7e843d8655d1b22e32
    municipales:
      2014:
        - url: https://www.data.gouv.fr/s/resources/elections-municipales-2014-resultats-par-bureaux-de-vote/20150925-122128/MN14_Bvot_T1T2.txt
          date: 25/09/2015
          hash: fe8ae42befb8e006dce1d959bee237449c9f39506c940e68c9b49a20f4363570
