insee:
  cog:
    communes:
      url: https://www.insee.fr/fr/statistiques/fichier/4316069/communes2020-csv.zip
      date: 04/2019
      hash: a690f63bdcac9c65e1d1e8816f024ca02b9f20df5fd30b93bbcb58bda563d181
    cantons:
      url: https://www.insee.fr/fr/statistiques/fichier/4316069/canton2020-csv.zip
      date: 01/2019
      hash: c683a13901ff447a3748fa4662b0b35951d2210e0b5b8b0f9db0f1346a88a338
    departements:
      url: https://www.insee.fr/fr/statistiques/fichier/4316069/departement2020-csv.zip
      date: 01/2019
      hash: b89413321f30118756c9f4502e756279cbcaf089b3a0e5980c32bc14981d86c1
    regions:
      url: https://www.insee.fr/fr/statistiques/fichier/4316069/region2020-csv.zip
      date: 01/2019
      hash: 029877a27e283ec7de824a398eb443ef5e34dbd16fc5ba8a41659a2bebca48af

  population:
    url: https://www.insee.fr/fr/statistiques/fichier/4265429/ensemble.zip
    date: 30/12/2019
    hash: 7c12879f5812772c29ab32f40310ef20ee16082c96f34b64152bb83cb1359307

  intercommunalite:
    epci:
      url: https://www.insee.fr/fr/statistiques/fichier/2510634/Intercommunalite-Metropole_au_01-01-2020.zip
      date: 01/2020
      hash: fbf7dbcd7a995b9fa68c9861d8e5d3ff98c0978ad588d0db4fd7f81a42f85a9c

  decoupage_communal:
    url: https://www.insee.fr/fr/statistiques/fichier/2028028/table-appartenance-geo-communes-19.zip
    date: 01/2019
    hash: af1a56188813d578dd07b5adc7f74c87e0a0b140049dc9e0c544f7b81f4610ca


ign:
  admin-express:
    version-cog:
      url: ftp://Admin_Express_ext:Dahnoh0eigheeFok@ftp3.ign.fr/ADMIN-EXPRESS-COG_2-1__SHP__FRA_WGS84G_2020-11-20.7z
      date: 20/11/2020
      hash: 1b80affb74f93b0fd9fd89612c4dfbbde6d0b3f7c1562822c8ef1461bb7cf42a
#    classique:
#      url: ftp://Admin_Express_ext:Dahnoh0eigheeFok@ftp3.ign.fr/ADMIN-EXPRESS_2-2__SHP__FRA_L93_2020-01-16.7z.001
#      date: 01/2020
#      hash: 635d5625ea0e4a311d8eb8af10c46fe081385e2840be2f558d457ef814038f20


interieur:
  rne:
    municipaux:
      url: https://static.data.gouv.fr/resources/repertoire-national-des-elus-1/20201202-174800/1-rne-cm.txt
      date: 02/12/2020
      hash: e22e73267fb26597627f548ec10548554759f10070f3121e8deaec9001c95d25
    epci:
      url: https://static.data.gouv.fr/resources/repertoire-national-des-elus-1/20201202-174822/2-rne-epci.txt
      date: 02/12/2020
      hash: 85feac28513250b4a2db896ee72f69fc3c3ff99159fe86c1acea0d5b97cc5036
  resultats_electoraux:
    presidentielles:
      2017:
        tour1:
          url: https://www.data.gouv.fr/s/resources/election-presidentielle-des-23-avril-et-7-mai-2017-resultats-definitifs-du-1er-tour-par-bureaux-de-vote/20170427-100955/PR17_BVot_T1_FE.txt
          date: 04/2017
          hash: 1eb1e4358a8af59ebc86ff7e0e4a2ee175f6cf516e4598cd955193064fc91e6a
        tour2:
          url: https://www.data.gouv.fr/s/resources/election-presidentielle-des-23-avril-et-7-mai-2017-resultats-definitifs-du-2nd-tour-par-bureaux-de-vote/20170511-093541/PR17_BVot_T2_FE.txt
          date: 05/2017
          hash: 2b6137b64957b9bfff24436cf859aad15e8b155b837b182eebff71c21fc82798
    legislatives:
      2017:
        tour1:
          url: https://www.data.gouv.fr/s/resources/elections-legislatives-des-11-et-18-juin-2017-resultats-par-bureaux-de-vote-du-1er-tour/20170613-100441/Leg_2017_Resultats_BVT_T1_c.txt
          date: 06/2017
          hash: f0e0d5149af2a52b843712329889f607efd589dd4836f0ec1334eb8b164e5fdb
        tour2:
          url: https://www.data.gouv.fr/s/resources/elections-legislatives-des-11-et-18-juin-2017-resultats-du-2nd-tour-par-bureaux-de-vote/20170620-094954/Leg_2017_Resultats_BVT_T2_c.txt
          date: 06/2017
          hash: 2d898b6bebcc401b79fe3ebbc0deb37d5dcc32c11ac3f5e8be0b0f006ee9eb8e
    europeennes:
      2019:
        url: https://static.data.gouv.fr/resources/resultats-des-elections-europeennes-2019/20190531-144007/resultats-definitifs-par-bureau-de-vote.txt
        date: 31/05/2019
        hash: a54a77872089f893145b9bad4d3d8479220bf60efa0fc3d0a81f54ede4d12208
      2014:
        url: https://www.data.gouv.fr/s/resources/elections-europeennes-2014-resultats-par-bureaux-de-vote/20150925-112120/ER14_BVOT.txt
        date: 25/09/2015
        hash: af1840b437db8a154f5b286c18a45d7534238ab8b9e73b7e843d8655d1b22e32
    municipales:
      2020:
        tour1:
          url: https://static.data.gouv.fr/resources/elections-municipales-2020-resultats/20200525-133745/2020-05-18-resultats-par-niveau-burvot-t1-france-entiere.txt
          date: 18/05/2020
          hash: ab2c17eccd3fc0358db8007a7faceb3697e51af847c2aada8018669a4e167071
          delimiter: "\t"
          corrected: ".csv"
        tour2:
          url: https://static.data.gouv.fr/resources/municipales-2020-resultats-2nd-tour/20200629-192438/resultats-par-niveau-burvot-t2-france-entiere.txt
          date: 30/06/2020
          hash: 07e1c3e1a547094e16250d3b659a2de19ea57e377ef0b586d6dbc6df27609c45
      2014:
        url: https://www.data.gouv.fr/s/resources/elections-municipales-2014-resultats-par-bureaux-de-vote/20150925-122128/MN14_Bvot_T1T2.txt
        date: 25/09/2015
        hash: fe8ae42befb8e006dce1d959bee237449c9f39506c940e68c9b49a20f4363570

laposte:
  codes_postaux:
    url: https://datanova.laposte.fr/explore/dataset/laposte_hexasmal/download/?format=csv&timezone=Europe/Berlin&lang=fr&use_labels_for_header=true&csv_separator=%2C
    extension: .csv
    hash: 5efee6567545417c7f109cb999c69383892803c58860644261e748b7cfe33d80

premier_ministre:
  annuaire_administration:
    url: http://lecomarquage.service-public.fr/donnees_locales_v2/all_latest.tar.bz2
    extension: .tar.bz2
    hash: 0ff7121606c81b572cbd6cf12a500b7caa90dad27d83ca9fd6d7ef3deed196f6

conseil_constitutionnel:
  parrainages2017:
    url: https://presidentielle2017.conseil-constitutionnel.fr/wp-content/uploads/2017/03/parrainagestotal.csv
    hash: 8af6c3fe6f2c57ed6751c9a1daa36b26ae873578601ada0aa5483833ef4c8371
